// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entrance_receipts.sql

package database

import (
	"context"

	"github.com/shopspring/decimal"
)

const createEntranceReceipt = `-- name: CreateEntranceReceipt :exec
INSERT INTO entrance_receipts (
    created_at, updated_at, truck_reg, trailer_reg, gross, tare, grain_type
    )
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateEntranceReceiptParams struct {
	TruckReg   string
	TrailerReg string
	Gross      decimal.Decimal
	Tare       decimal.Decimal
	GrainType  string
}

func (q *Queries) CreateEntranceReceipt(ctx context.Context, arg CreateEntranceReceiptParams) error {
	_, err := q.db.ExecContext(ctx, createEntranceReceipt,
		arg.TruckReg,
		arg.TrailerReg,
		arg.Gross,
		arg.Tare,
		arg.GrainType,
	)
	return err
}
