// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/shopspring/decimal"
)

type EntranceReceipt struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	TruckReg   string
	TrailerReg string
	Gross      decimal.Decimal
	Tare       decimal.Decimal
	GrainType  string
}
