-- +goose Up
CREATE TABLE entrance_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    truck_reg TEXT NOT NULL,
    trailer_reg TEXT NOT NULL,
    gross NUMERIC(12, 3) NOT NULL,
    tare NUMERIC(12, 3) NOT NULL,
    grain_type TEXT NOT NULL
);

-- +goose Down
DROP TABLE entrance_receipts;