-- +goose Up
CREATE TABLE purchases (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    suplier TEXT NOT NULL,
    price NUMERIC(12, 3) NOT NULL,
    quantity NUMERIC(12, 3) NOT NULL,
    grain_type TEXT NOT NULL
);

ALTER TABLE entrance_receipts
ADD COLUMN purchase_id INT NOT NULL REFERENCES purchases(id);

-- +goose Down
ALTER TABLE entrance_receipts
DROP COLUMN purchase_id; 

DROP TABLE purchases;