-- +goose Up
CREATE TABLE sales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    client TEXT NOT NULL,
    price NUMERIC(12, 3) NOT NULL,
    quantity NUMERIC(12, 3) NOT NULL,
    grain_type TEXT NOT NULL
);

ALTER TABLE exit_receipts
ADD COLUMN sale_id INT NOT NULL REFERENCES sales(id);

-- +goose Down
ALTER TABLE exit_receipts
DROP COLUMN sale_id; 

DROP TABLE sales;