-- +goose Up
CREATE TABLE transports (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    truck_reg TEXT NOT NULL,
    trailer_reg TEXT NOT NULL,
    net NUMERIC(12, 3) NOT NULL,
    sale_id INT NOT NULL REFERENCES sales(id),
    purchase_id INT NOT NULL REFERENCES purchases(id)
);

-- +goose Down
DROP TABLE transports;