-- +goose Up
CREATE TABLE companies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    vat_number TEXT NOT NULL UNIQUE,
    CONSTRAINT valid_vat CHECK (vat_number ~ '^[0-9]{9}$'),
    name TEXT NOT NULL UNIQUE,
    address TEXT NOT NULL
);

ALTER TABLE purchases ADD COLUMN suplier_id INT NOT NULL REFERENCES companies(id);
ALTER TABLE sales ADD COLUMN client_id INT NOT NULL REFERENCES companies(id);
ALTER TABLE transports ADD COLUMN suplier_id INT NOT NULL REFERENCES companies(id);
ALTER TABLE transports ADD COLUMN client_id INT NOT NULL REFERENCES companies(id);
ALTER TABLE sales DROP column client;
ALTER TABLE purchases DROP column suplier;


-- +goose Down
ALTER TABLE purchases DROP COLUMN company_id;
ALTER TABLE sales DROP COLUMN company_id;
ALTER TABLE transports DROP COLUMN suplier_id;
ALTER TABLE transports DROP COLUMN client_id;
DROP TABLE companies;